import "./globals.css"

import { Geist, Geist_Mono } from "next/font/google"
import React from "react"

import AppLayout from "@/app/app-layout"
import type { Metadata } from "next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <React.Suspense fallback={<div />}>
          {/* Suspense for client components using next/navigation */}
          <AppLayout>{children}</AppLayout>
        </React.Suspense>
      </body>
    </html>
  )
}
